### ISSUE TITLE
Where i can get credentialsLocation ?

### ISSUE THREAD

**Issue by uitlaber** [akarri2001/Notion-and-Google-Calendar-2-Way-Sync#2]
Hello, good work man!
Where i can get credentialsLocation ?
Can you help me little from anydesk or skype?

**Comment by Sjaakie-stud** [comment]
If you're on Windows, the credentialLocation is the path of the client_secret.json file; the file you've downloaded from your Google Api page. It therefore depends on where you have put this file what to fill in as credentialsLocation.

When you look at the edits in the pull requests section you can see you just have to change "client_secret.json" to "token.pkl" in this pathstring.
