### ISSUE TITLE
End Time Notion not appearing in GCal

### ISSUE THREAD

**Issue by Sjaakie-stud** [akarri2001/Notion-and-Google-Calendar-2-Way-Sync#3]
Hey! Thank you so much for this project! This is exactly what I have been looking for.

I however encouter a problem with the endtimes of events in Notion. If I've read it correctly in the added features you have mentioned that endtimes should be synced both ways. This works when I create an event in GCal; it shows up correctly. But if I enter an endtime in Notion it ends up with the default 60 minutes duration in GCal. 

Do I have to adjust something in the code to make this work? I have read the code from top to bottom but can't seem to find the place where this should be adjusted.

**Comment by akarri2001** [comment]
Hey! Thanks for raising this issue! Would you be able to tell me if this occurs when updating a GCal event or bringing a new event over to GCal?

**Comment by akarri2001** [comment]
Found the errors on lines 218 and 311, I'll be working to fix those soon.

**Comment by Sjaakie-stud** [comment]
Looking forward to the fixes! (I've described the instances when the error occured below.)

I've checked it:

It occurs for both occasions. When I enter an event in my Notion database, e.g from 10am to 2pm, it will end up in GCal as 10am-11am, and automatically changed in Notion form 10am-11am.  
When I change the times in Notion, for example when I edit the example above, in Notion from 10am to 9am, the event changes in both GCal and Notion to 9am-10am.

**Comment by akarri2001** [comment]
Got it. Thank you again for raising the issue! I just have to add in a couple if/else statements to make set the eventEndTime variable correctly.

**Comment by akarri2001** [comment]
Hey, just uploaded some new code. Could you give it a go now?

**Comment by Sjaakie-stud** [comment]
As far as I can tell it works perfectly! Thank you!
